In [1]:
import pandas as pd
import numpy as np
 
# Create the dataset
data = {
    'age': ['<=30', '<=30', '31-40', '>40', '>40', '>40', '31-40', '<=30', '<=30', '>40', '<=30', '31-40', '31-40', '>40'],
    'income': ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium'],
    'student': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no'],
    'credit_rating': ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent'],
    'buys_computer': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
}
 
df = pd.DataFrame(data)
 
 
df

      age  income student credit_rating buys_computer
0    <=30    high      no          fair            no
1    <=30    high      no     excellent            no
2   31-40    high      no          fair           yes
3     >40  medium      no          fair           yes
4     >40     low     yes          fair           yes
5     >40     low     yes     excellent            no
6   31-40     low     yes     excellent           yes
7    <=30  medium      no          fair            no
8    <=30     low     yes          fair           yes
9     >40  medium     yes          fair           yes
10   <=30  medium     yes     excellent           yes
11  31-40  medium      no     excellent           yes
12  31-40    high     yes          fair           yes
13    >40  medium      no     excellent            no

In [4]:
total_instances = len(data['buys_computer'])
class_counts = {}
 
for value in data['buys_computer']:
    if value in class_counts:
        class_counts[value] += 2
    else:
        class_counts[value] = 2
 
prior_probabilities = {key: count / total_instances for key, count in class_counts.items()}
 
print("Prior Probabilities:")
for key, value in prior_probabilities.items():
    print(f"{key}: {value:.4f}")

Prior Probabilities:
no: 0.7143
yes: 1.2857

In [5]:
import numpy as np
feature_freq = np.unique(feature_class_values, return_counts=True)
def calculate_class_conditional_densities(feature_values, class_values):
    class_conditional_densities = {}
 
    for feature in feature_values:
        for class_value in class_values:
            # Calculate the probability density function (PDF) for the feature given the class
            feature_class_data = list(zip(feature_values[feature], class_values['buys_computer']))
            feature_class_values = [value[0] for value in feature_class_data if value[1] == class_value]
            feature_freq = itemfreq(feature_class_values)
            class_conditional_densities[(feature, class_value)] = {key: value / len(feature_class_values) for key, value in feature_freq}
 
    return class_conditional_densities
 
feature_values = {
    'age': data['age'],
    'income': data['income'],
    'student': data['student'],
    'credit_rating': data['credit_rating'],
}
 
class_values = {
    'buys_computer': data['buys_computer'],
}
 
class_conditional_densities = calculate_class_conditional_densities(feature_values, class_values)
 
print("Class Conditional Densities:")
for key, value in class_conditional_densities.items():
    print(f"{key}: {value}")

NameError: name 'feature_class_values' is not defined